name = input("Enter your name: ")
surname = input("Enter your surname: ")
print("Hello, " + name + " " + surname + "!")
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b)
print("Exponentiation:", a ** b)
print("Integer Division:", a // b)
print("Remainder:", a % b)
print(a < b)
print(a <= b)
print(a != b)
print(a == b)